name: steam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  webview_flutter: ^4.13.0
  provider: ^6.1.5+1
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
